apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudlab-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudlab.labels" . | nindent 4 }}
data:
  TZ: {{ .Values.global.tz | quote }}
  SERVER_PORT: {{ .Values.backend.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: "6379"
  CLOUDLAB_CORS_ORIGINS: {{ .Values.corsOrigins | quote }}
  CLOUDLAB_WAIT_FOR: "{{ .Values.config.postgresHost }}:5432 {{ .Values.config.redisHost }}:6379"
