#!/usr/bin/env bash
# Send one real Discord webhook message for interview evidence.
# Usage:
#   export DISCORD_WEBHOOK_URL='https://discord.com/api/webhooks/...'
#   ./scripts/demo-discord-test.sh
# Or load from .env automatically.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ -z "${DISCORD_WEBHOOK_URL:-}" && -f .env ]]; then
  # shellcheck disable=SC1091
  set -a
  # only pull the one var if present
  DISCORD_WEBHOOK_URL=$(grep -E '^DISCORD_WEBHOOK_URL=' .env | tail -1 | cut -d= -f2- | tr -d '"' | tr -d "'")
  set +a
fi

if [[ -z "${DISCORD_WEBHOOK_URL:-}" ]]; then
  cat <<'EOF'
DISCORD_WEBHOOK_URL is not set.

1) Discord 서버 → 채널 설정 → 연동 → 웹후크 → 새 웹후크 → URL 복사
2) export DISCORD_WEBHOOK_URL='https://discord.com/api/webhooks/...'
   또는 .env 에 DISCORD_WEBHOOK_URL=... 추가
3) ./scripts/demo-discord-test.sh
4) Discord 메시지 스크린샷 → docs/assets/demo/discord-alert.png

Also test Alertmanager path (if stack is up):
  ./scripts/demo-discord-test.sh --alertmanager
EOF
  exit 1
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
HOST=$(hostname 2>/dev/null || echo lab)

send_webhook() {
  local title="$1" color="$2" desc="$3"
  curl -fsS -H "Content-Type: application/json" \
    -d "$(jq -n \
      --arg title "$title" \
      --argjson color "$color" \
      --arg desc "$desc" \
      --arg ts "$TS" \
      --arg host "$HOST" \
      '{
        username: "CloudLab Demo",
        embeds: [{
          title: $title,
          description: $desc,
          color: $color,
          fields: [
            {name: "Source", value: "demo-discord-test.sh", inline: true},
            {name: "Host", value: $host, inline: true},
            {name: "Time (UTC)", value: $ts, inline: false}
          ],
          footer: {text: "Interview evidence — CloudLab ops platform"}
        }]
      }')" \
    "$DISCORD_WEBHOOK_URL"
  echo
}

if [[ "${1:-}" == "--alertmanager" ]]; then
  echo "==> Firing test alert via Alertmanager API (also try webhook embed)"
  # Alertmanager v2 API — creates a temporary firing alert
  curl -fsS -X POST "http://127.0.0.1:9093/api/v2/alerts" \
    -H "Content-Type: application/json" \
    -d "[
      {
        \"labels\": {
          \"alertname\": \"CloudLabDemoAlert\",
          \"severity\": \"warning\",
          \"service\": \"cloudlab-demo\",
          \"instance\": \"demo\"
        },
        \"annotations\": {
          \"summary\": \"CloudLab interview demo alert\",
          \"description\": \"Synthetic alert for portfolio demo evidence\"
        },
        \"startsAt\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
      }
    ]" && echo "Alertmanager accepted test alert" || echo "Alertmanager post failed (is stack up?)"
fi

echo "==> Sending Discord embed..."
if command -v jq >/dev/null 2>&1; then
  send_webhook "CloudLab Demo Alert ✓" 15105570 \
    "면접 데모용 **실제 Discord 연동** 테스트입니다.\\nDashboard · Alertmanager · CI/CD 스토리 증거."
else
  # minimal fallback without jq
  curl -fsS -H "Content-Type: application/json" \
    -d "{\"content\":\"**CloudLab Demo Alert** — interview evidence @ ${TS} (${HOST})\"}" \
    "$DISCORD_WEBHOOK_URL"
  echo
fi

OUT_DIR="$ROOT/docs/assets/demo"
mkdir -p "$OUT_DIR"
cat > "$OUT_DIR/discord-test-receipt.md" <<EOF
# Discord test receipt

| Field | Value |
|-------|--------|
| Time (UTC) | ${TS} |
| Host | ${HOST} |
| Webhook | configured (URL not stored here) |
| Status | **HTTP send attempted — check Discord channel** |

## Capture for README

1. Open the Discord channel that received the message.
2. Screenshot the CloudLab embed (hide personal server names if needed).
3. Save as: \`docs/assets/demo/discord-alert.png\`
4. Optional: also screenshot Dashboard **Alerts** page as \`alerts-page.png\`.

Receipt generated by \`scripts/demo-discord-test.sh\`.
EOF

echo "Receipt: docs/assets/demo/discord-test-receipt.md"
echo "Next: save Discord screenshot to docs/assets/demo/discord-alert.png"
